version: '3'
networks:
  codo:
services:
  codo-kerrigan:
    restart: unless-stopped
    image: codo_kerrigan_image
    networks:
      - codo
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    ports:
      - "8030:8000"