version: '3'
networks:
  codo:
services:
  codo-kerrigan:
    image: codo-kerrigan-image
    networks:
      - codo
    ports:
      - "8030:8000"
    restart: unless-stopped
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
