FROM centos:7
ENV LANG en_US.UTF-8
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 1. 安装基本依赖
RUN yum update -y && \
    yum install epel-release -y && \
    yum update -y && \
    yum install wget unzip epel-release nginx  \
        xz gcc automake zlib-devel openssl-devel \
        supervisor  groupinstall development  \
        libxslt-devel libxml2-devel libcurl-devel git  python3 python3-pip -y && \
    yum clean all && rm -rf /var/cache/yum/*

# 2. 准备python
#RUN wget https://www.python.org/ftp/python/3.6.6/Python-3.6.6.tar.xz
#RUN xz -d Python-3.6.6.tar.xz && tar xvf Python-3.6.6.tar && cd Python-3.6.6 && ./configure && make && make install

# 3. 安装pip依赖
RUN pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple --upgrade pip && \
    pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -U git+https://github.com/ss1917/ops_sdk.git

CMD ["/usr/bin/supervisord"]
