FROM registry.cn-hangzhou.aliyuncs.com/sourcegarden/python:centos7-3.6

# 4. 复制代码
RUN mkdir -p /var/www/
ADD . /var/www/kerrigan/

# 5. 安装pip依赖
RUN pip3 install -r /var/www/kerrigan/doc/requirements.txt

# 6. 初始化生成表结构
#RUN python3 /var/www/kerrigan/db_sync.py

# 7. 日志
VOLUME /var/log/

# 8. 准备文件
COPY doc/nginx_ops.conf /etc/nginx/conf.d/default.conf
COPY doc/supervisor_ops.conf  /etc/supervisord.conf

EXPOSE 80
CMD ["/usr/bin/supervisord"]