FROM registry.cn-hangzhou.aliyuncs.com/sourcegarden/python:centos7-3.6

ENV cookie_secret nJ2oZis0V/xlArY2rzpIE6ioC9/KlqR2fd59sD=UXZJ=3OeROB

RUN mkdir -p /var/www/
ADD ../  /var/www/kerrigan/

RUN pip3 install -r /var/www/kerrigan/doc/requirements.txt

#RUN python3 /var/www/kerrigan/db_sync.py

VOLUME /var/log/

COPY nginx_ops.conf /etc/nginx/conf.d/default.conf
COPY supervisor_ops.conf  /etc/supervisord.conf

EXPOSE 80
CMD ["/usr/bin/supervisord"]
